---
- name: NXOS running-config backup
  hosts: my_nxos_hosts
  gather_facts: false
  serial:
  vars:
####The following will save NXOS configurations to specified directory with date/time

  - name: Get date/time
    setup:
	  filter: "ansible_date_time"
	  gather_subset:
	run_once: true
	
  - name: Set DTG fact
    set_fact:
	  DTG: "{{ ansible_date_time }}"
	  state: directory
  - name: Save runfig to PWD
    nxos_config:
	 backup:yes
	 backup_options:
	  filename: "{{ file_path }}{{ DTG }}/{{ ansible_net_hostname }}.cfg"
	register: backup_result
	
  - name: Display backup location
    ansible.builtin.debug:
	 msg: "Running config {{ ansible_net_hostname }}.cfg has been saved too {{ backup_result.backup.path }}"