---

'''Hosts file that define Vars for Individual hosts. Use Groups file if one VAR can be applied to mulitple units'''

# myAccessSwitch:
#     hostname: "switchitup.org"
#     groups: 
#         - access_switches
#         - user

# myRouterUpstream:
#     hostname: "10.10.10.10"
#     groups: 
#         - cisco_iosxe
#         - routers
