---

- Name: Cisco IOS-XE Cataylst running-configuration back-up
  Hosts: my_ios_hosts
  gather_facts: false
  serial: 

###The following will save a running config of a Cataylst switch to a PWD variable it pulls from the inventory.
###creating a new folder of the current date
  tasks:
  - name: Get date/time
    setup:
      filter: "ansible_date_time"
    gather_subset:
      run_once: true
	
  - name: Set date/time variable 
    set_fact:
      DTG: "{{ ansible_date_time }}"
    run_once: true
	
  - name: Create DIR
    file:
      path: "{{ running_configuration_save_path }}{{ DTG }}"
      state: directory
    run_once: true
	
  - name: IOS Device Reachable
    ios_facts:
      gather_subset: all
	  
  - name: Back-up config
    ios_config:
      backup: yes
      backup_options:
        filename: "{{ running_configuration_save_path }}{{ DTG}}/{{ ansible_net_hostname }}.cfg"