---

- Name: Cisco IOS-XE configuration push
  Hosts: 
  gather_facts: false
  serial: 
  vars: 
    running_config_pwd: "Your/PWD/HEre"

###The following will push Cataylst configurations as running-configs to selected devices

  - name: IOS Device reachability
    ios_facts:
      gather_subset: all
	  
  - name: Push config to switch
    ios_config:
	    src: "{{ running_config_pwd }}"
